-- Kora Supabase schema for coin cache + user data.
-- This migration is safe to commit: no secrets are stored here.

create extension if not exists pgcrypto;

create table if not exists public.coins (
  uuid text primary key,
  symbol text not null,
  name text not null,
  icon_url text null,
  rank integer not null,
  price numeric not null default 0,
  market_cap numeric not null default 0,
  volume_24h numeric not null default 0,
  change_24h numeric not null default 0,
  updated_at timestamptz not null default now()
);

create index if not exists coins_rank_idx on public.coins (rank);
create index if not exists coins_updated_at_idx on public.coins (updated_at desc);

create table if not exists public.coin_history (
  id bigint generated by default as identity primary key,
  coin_uuid text not null references public.coins (uuid) on delete cascade,
  ts timestamptz not null,
  price numeric not null,
  constraint coin_history_coin_ts_unique unique (coin_uuid, ts)
);

create index if not exists coin_history_coin_uuid_idx on public.coin_history (coin_uuid);
create index if not exists coin_history_ts_idx on public.coin_history (ts desc);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  coin_uuid text not null references public.coins (uuid) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_coin_unique unique (user_id, coin_uuid)
);

create index if not exists favorites_user_id_idx on public.favorites (user_id);
create index if not exists favorites_coin_uuid_idx on public.favorites (coin_uuid);

create table if not exists public.portfolio_holdings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  coin_uuid text not null references public.coins (uuid) on delete cascade,
  quantity numeric not null default 0,
  avg_buy_price numeric null,
  updated_at timestamptz not null default now(),
  constraint portfolio_holdings_user_coin_unique unique (user_id, coin_uuid)
);

create index if not exists portfolio_holdings_user_id_idx
  on public.portfolio_holdings (user_id);
create index if not exists portfolio_holdings_coin_uuid_idx
  on public.portfolio_holdings (coin_uuid);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  coin_uuid text not null references public.coins (uuid) on delete restrict,
  side text not null check (side in ('buy', 'sell')),
  amount_usd numeric not null,
  price numeric null,
  status text not null default 'pending'
    check (status in ('pending', 'filled', 'rejected', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists orders_user_id_idx on public.orders (user_id);
create index if not exists orders_coin_uuid_idx on public.orders (coin_uuid);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_coins_updated_at on public.coins;
create trigger trg_coins_updated_at
before update on public.coins
for each row execute function public.set_updated_at();

drop trigger if exists trg_portfolio_holdings_updated_at on public.portfolio_holdings;
create trigger trg_portfolio_holdings_updated_at
before update on public.portfolio_holdings
for each row execute function public.set_updated_at();

alter table public.coins enable row level security;
alter table public.coin_history enable row level security;
alter table public.favorites enable row level security;
alter table public.portfolio_holdings enable row level security;
alter table public.orders enable row level security;

-- Coins and history are readable for all clients (anon/auth) so dashboards can load quickly.
drop policy if exists coins_public_read on public.coins;
create policy coins_public_read
on public.coins
for select
using (true);

drop policy if exists coin_history_public_read on public.coin_history;
create policy coin_history_public_read
on public.coin_history
for select
using (true);

-- Favorites: user-scoped CRUD.
drop policy if exists favorites_select_own on public.favorites;
create policy favorites_select_own
on public.favorites
for select
using (user_id = auth.uid());

drop policy if exists favorites_insert_own on public.favorites;
create policy favorites_insert_own
on public.favorites
for insert
with check (user_id = auth.uid());

drop policy if exists favorites_update_own on public.favorites;
create policy favorites_update_own
on public.favorites
for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists favorites_delete_own on public.favorites;
create policy favorites_delete_own
on public.favorites
for delete
using (user_id = auth.uid());

-- Portfolio holdings: user-scoped CRUD.
drop policy if exists portfolio_holdings_select_own on public.portfolio_holdings;
create policy portfolio_holdings_select_own
on public.portfolio_holdings
for select
using (user_id = auth.uid());

drop policy if exists portfolio_holdings_insert_own on public.portfolio_holdings;
create policy portfolio_holdings_insert_own
on public.portfolio_holdings
for insert
with check (user_id = auth.uid());

drop policy if exists portfolio_holdings_update_own on public.portfolio_holdings;
create policy portfolio_holdings_update_own
on public.portfolio_holdings
for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists portfolio_holdings_delete_own on public.portfolio_holdings;
create policy portfolio_holdings_delete_own
on public.portfolio_holdings
for delete
using (user_id = auth.uid());

-- Orders: user-scoped CRUD.
drop policy if exists orders_select_own on public.orders;
create policy orders_select_own
on public.orders
for select
using (user_id = auth.uid());

drop policy if exists orders_insert_own on public.orders;
create policy orders_insert_own
on public.orders
for insert
with check (user_id = auth.uid());

drop policy if exists orders_update_own on public.orders;
create policy orders_update_own
on public.orders
for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists orders_delete_own on public.orders;
create policy orders_delete_own
on public.orders
for delete
using (user_id = auth.uid());
